"""
UT Template for JUnit 5 test generation
"""

# Template for basic test class
TEST_CLASS_TEMPLATE = '''package {package};

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

{imports}

/**
 * Unit tests for {class_name}
 * Generated by Multi-Agent UT Generation System
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("Tests for {class_name}")
class {class_name}Test {{

    {mock_fields}

    {class_name} {instance_name};

    @BeforeEach
    void setUp() {{
        {instance_name} = new {class_name}({constructor_args});
    }}

    {test_methods}
}}
'''

# Template for mock field
MOCK_FIELD_TEMPLATE = '    @Mock\n    private {type} {name};'

# Template for test method
TEST_METHOD_TEMPLATE = '''
    @Test
    @DisplayName("{display_name}")
    void {method_name}() {{
        // Arrange
        {arrange}

        // Act
        {act}

        // Assert
        {assert}
    }}
'''

# Template for normal path test
NORMAL_PATH_TEST = '''
    @Test
    @DisplayName("Should return result when valid input")
    void shouldReturnResultWhenValidInput() {{
        // Arrange
        {arrange_setup}

        // Act
        {act_statement}

        // Assert
        {assert_statements}
        verify({mock_name}).{method_call};
    }}
'''

# Template for boundary condition test
BOUNDARY_TEST = '''
    @Test
    @DisplayName("Should handle null input")
    void shouldHandleNullInput() {{
        // Arrange
        {arrange_setup}

        // Act & Assert
        assertThrows({exception_type}.class, () -> {{
            {act_statement}
        }});
    }}
'''

# Template for exception test
EXCEPTION_TEST = '''
    @Test
    @DisplayName("Should throw exception when invalid input")
    void shouldThrowExceptionWhenInvalidInput() {{
        // Arrange
        {arrange_setup}

        // Act & Assert
        {exception_type} exception = assertThrows({exception_type}.class, () -> {{
            {act_statement}
        }});

        assertEquals("{expected_message}", exception.getMessage());
    }}
'''

# Template for entity test
ENTITY_TEST = '''
    @Test
    @DisplayName("Should create with valid fields")
    void shouldCreateWithValidFields() {{
        // Arrange
        {arrange_setup}

        // Act
        {class_name} result = new {class_name}({constructor_args});

        // Assert
        assertNotNull(result);
        {assert_statements}
    }}

    @Test
    @DisplayName("Should equals when same id")
    void shouldEqualsWhenSameId() {{
        // Arrange
        {class_name} obj1 = new {class_name}({constructor_args});
        {class_name} obj2 = new {class_name}({constructor_args});

        // Assert
        assertEquals(obj1, obj2);
    }}
'''

# Template for controller test
CONTROLLER_TEST = '''
    @Test
    @DisplayName("Should return 200 when valid request")
    void shouldReturn200WhenValidRequest() {{
        // Arrange
        when({service_name}.{method_name}({args})).thenReturn({return_value});

        // Act
        {response_type} response = {instance_name}.{method_name}({args});

        // Assert
        assertNotNull(response);
        verify({service_name}).{method_name}({args});
    }}
'''


classUTTemplate:
    """Template utilities for UT generation"""

    @staticmethod
    def get_imports(class_type: str) -> str:
        """Get required imports based on class type"""
        common_imports = [
            "import org.junit.jupiter.api.Test;",
            "import org.junit.jupiter.api.DisplayName;",
            "import org.junit.jupiter.api.BeforeEach;",
            "import org.junit.jupiter.api.extension.ExtendWith;",
            "import org.mockito.InjectMocks;",
            "import org.mockito.Mock;",
            "import org.mockito.junit.jupiter.MockitoExtension;",
            "import static org.junit.jupiter.api.Assertions.*;",
            "import static org.mockito.Mockito.*;"
        ]

        type_imports = {
            "controller": ["import org.springframework.http.ResponseEntity;"],
            "service": [],
            "entity": [],
            "repository": ["import java.util.Optional;"]
        }

        imports = common_imports + type_imports.get(class_type, [])
        return "\n".join(imports)

    @staticmethod
    def generate_test_content(class_name: str, package_name: str, class_type: str,
                             mock_fields: list, constructor_args: str,
                             test_methods: str) -> str:
        """Generate complete test class content"""
        instance_name = class_name[0].lower() + class_name[1:] if len(class_name) > 1 else class_name

        return TEST_CLASS_TEMPLATE.format(
            package=package_name,
            class_name=class_name,
            mock_fields="\n".join(mock_fields) if mock_fields else "    // No dependencies",
            instance_name=instance_name,
            constructor_args=constructor_args or "",
            test_methods=test_methods
        )

    @staticmethod
    def format_test_method(test_name: str, display_name: str, arrange: str,
                           act: str, assert_statements: str) -> str:
        """Format a test method"""
        return TEST_METHOD_TEMPLATE.format(
            method_name=test_name,
            display_name=display_name,
            arrange=arrange or "// No setup needed",
            act=act or "// No action",
            assert=assert_statements or "// No assertions"
        )